name: Keep Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl -X GET https://todolist-deployment.onrender.com
